fix K2P and other compile fail.

diff --git a/trunk/build_firmware_modify b/trunk/build_firmware_modify
--- a/trunk/build_firmware_modify
+++ b/trunk/build_firmware_modify
@@ -1,13 +1,20 @@
 #!/bin/sh
 
-[ -z "$1" ] && echo "Please run '$0 PRODUCT_NAME' to start build (see 'configs/templates/') " && exit 1 
+key=$1
+if [ "${key}" != "" ]; then
+echo key=${key}
+if echo ${key} | grep -q -E -v "^RT-N56U_"; then
+	[ -z "$1" ] && echo "Please run '$0 PRODUCT_NAME' to start build (see 'configs/templates/') " && exit 1 
 
-if [ ! -f configs/templates/$1.config ] ; then
-	echo "configs/templates/$1.config not found "
-	exit 1
+	if [ ! -f configs/templates/$1.config ] ; then
+		echo "configs/templates/$1.config not found "
+		exit 1
+	fi
+
+	cp -f configs/templates/$1.config .config
 fi
-
-cp -f configs/templates/$1.config .config
+echo build ${key}...
+fi
 
 ROOTDIR=`pwd`
 export ROOTDIR=$ROOTDIR
@@ -151,10 +158,10 @@ rm -rf "$dir_wifi_dst/rt5392"
 rm -rf "$dir_wifi_dst/rt5592"
 rm -rf "$dir_wifi_dst/rt3593"
 rm -rf "$dir_wifi_dst/mt7610"
-rm -rf "$dir_wifi_dst/mt76x2"
-rm -rf "$dir_wifi_dst/mt76x3"
+# rm -rf "$dir_wifi_dst/mt76x2"
+# rm -rf "$dir_wifi_dst/mt76x3"
 rm -rf "$dir_wifi_dst/mt7628"
-rm -rf "$dir_wifi_dst/mt7615"
+# rm -rf "$dir_wifi_dst/mt7615"
 mkdir -p "$dir_wifi_dst/mt7615/embedded"
 cp -f "$dir_wifi_src/rtpci/4.4.2.1/mt7615/embedded/Kconfig" "$dir_wifi_dst/mt7615/embedded/Kconfig"
 
@@ -525,6 +532,9 @@ fi
 # 	func_disable_kernel_param "CONFIG_SOUND"
 # fi
 #######################################################################
+if [ "$1" != "" ]; then
+	echo --------------------------${key}--------------------------------
+fi
 echo --------------------------MAKE-DEP--------------------------------
 if [ "$CONFIG_WITHOUT_KERNEL" != "y" ] ; then
 make dep
